name: PMIP4-midHolocene
channels:
  - conda-forge
dependencies:
  - xarray
  - cartopy
  - regionmask
  - cftime
  - scikit-learn
  # xESMF can fail with esmpy 8. due to parallel IO build issues
  - xesmf
  - esmpy=7.1.0
  # jupyter-related
  - jupyterlab
