name: PMIP4-midHolocene
channels:
  - conda-forge
dependencies:
  - xarray
  - cartopy
  - cftime
  - scikit-learn
  # Regionmask isn't compilign with this set up, due to a missing libpoppler.  One suggestion is constrain the poppler package. 
  - regionmask
  - poppler<0.62
  # xESMF can fail with esmpy 8. due to parallel IO build issues
  - xesmf
  - esmpy=7.1.0
  # jupyter-related
  - jupyterlab
