name: PMIP4-midHolocene
channels:
  - conda-forge
dependencies:
  - xarray
  - cartopy
  - cftime
  - scikit-learn
  # Regionmask is having problems importing, due to a missing libpoppler. I'm going to how this is fixed by the time you try it.. 
  - regionmask
  # xESMF can fail with esmpy 8. due to parallel IO build issues
  - xesmf
  - esmpy=7.1.0
  # jupyter-related
  - jupyterlab
