name: pangeo
channels:
  - conda-forge
dependencies:
  - python
  # core scipy packages
  - numpy
  - scipy
  - xarray
  - scikit-learn
  # geospatial
  - iris
  - cartopy
  - geopandas
  - rasterio
  - netcdf4
  - h5py
  - h5netcdf
  - regionmask
  - cftime
  # xESMF can fail with esmpy 8. due to parallel IO build issues
  - xesmf
  - esmpy=7.1.0
  # jupyter-related
  - nbserverproxy
  - jupyter
  - jupyterlab
  # xarray-related
  - xgcm
  - xrft
