name: pangeo
channels:
  - conda-forge
dependencies:
  - python
  # core scipy packages
  - numpy
  - scipy
  - xarray
  # geospatial
  - iris
  - cartopy
  - geopandas
  - rasterio
  - netcdf4
  - h5py
  - h5netcdf
  - xesmf
  - regionmask
  - cftime
  # jupyter-related
  - nbserverproxy
  - jupyter
  - jupyterlab
  # xarray-related
  - xgcm
  - xrft
